name: themealdb_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # http: ^1.2.2
  cached_network_image: ^3.3.1
  flutter_spinkit: ^5.2.1
  dio: ^5.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts-exo2/
    - assets/font-playwrite/
    - assets/font-plawrite-cu/
  fonts:
    - family: Exo2
      fonts:
        - asset: assets/fonts-exo2/Exo2-Black.ttf
          weight: 900
        - asset: assets/fonts-exo2/Exo2-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts-exo2/Exo2-Bold.ttf
          weight: 700
        - asset: assets/fonts-exo2/Exo2-SemiBold.ttf
          weight: 600
        - asset: assets/fonts-exo2/Exo2-Medium.ttf
          weight: 500
        - asset: assets/fonts-exo2/Exo2-Regular.ttf
          weight: 400
        - asset: assets/fonts-exo2/Exo2-Light.ttf
          weight: 300
        - asset: assets/fonts-exo2/Exo2-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts-exo2/Exo2-Thin.ttf
          weight: 100
    - family: Playwrite
      fonts:
        - asset: assets/font-playwrite/PlaywriteHRLijeva-Regular.ttf
          weight: 400
        - asset: assets/font-playwrite/PlaywriteHRLijeva-Light.ttf
          weight: 300
        - asset: assets/font-playwrite/PlaywriteHRLijeva-ExtraLight.ttf
          weight: 200
        - asset: assets/font-playwrite/PlaywriteHRLijeva-Thin.ttf
          weight: 100
    - family: Playwrite-cu
      fonts:
        - asset: assets/font-plawrite-cu/PlaywriteCU-Regular.ttf
          weight: 400
        - asset: assets/font-plawrite-cu/PlaywriteCU-Light.ttf
          weight: 300
        - asset: assets/font-plawrite-cu/PlaywriteCU-ExtraLight.ttf
          weight: 200
        - asset: assets/font-plawrite-cu/PlaywriteCU-Thin.ttf
          weight: 100